name: Rfam SQL Runner
on:
  push:
    paths: [ "sql/**/*.sql" ]
  pull_request:
    paths: [ "sql/**/*.sql" ]
  workflow_dispatch: {}
jobs:
  run-rfam-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -y && sudo apt-get install -y mysql-client
      - id: changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }} --depth=1
            range="origin/${{ github.base_ref }}...${{ github.sha }}"
          else
            range="${{ github.event.before }}...${{ github.sha }}"
          fi
          files=$(git diff --name-only "$range" | grep -E '^sql/.*\.sql$' || true)
          { echo "changed<<EOF"; echo "$files"; echo "EOF"; } >> "$GITHUB_OUTPUT"
      - if: steps.changes.outputs.changed != ''
        run: |
          chmod +x scripts/run_sql.sh
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            ./scripts/run_sql.sh "$file"
          done <<< "${{ steps.changes.outputs.changed }}"
      - if: steps.changes.outputs.changed != ''
        uses: actions/upload-artifact@v4
        with: { name: rfam-query-results, path: out/*.out, if-no-files-found: ignore }
      - if: steps.changes.outputs.changed == ''
        run: echo "No sql/*.sql files changed."
